title: Some Rich Asshole
tagline: Browser add-on that replaces "Donald Trump" with "Some Rich Asshole"
fullurl: "http://SomeRichAsshole.com" #used for fb share content
fbsharetext: Make the news more honest. And snarky. Browser add-on that replaces "Donald Trump" with "Some Rich Asshole". Available for Chrome and Firefox.
fbshareimg: fb-share.jpg
